function createWhiteAlchemy(){
	var whiteAlchemy = [];

	//0: link
	//1: name
	//2: level
	//3: price
	//4: rarity

	//whiteAlchemy.push([link,name,level,price,rarity]);

	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1190','Black Powder (Dose or Round)',0,1,1]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1188','Aromatic Ammunition',2,5,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1190','Black Powder (Horn)',2,5,1]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1193','Exsanguinating Ammunition',4,15,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1195','Glue Bullet',4,16,1]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1192','Eroding Bullet',5,22,1]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1190','Black Powder (Keg)',6,50,1]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1193','Exsanguinating Ammunition (Greater)',8,80,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1193','Exsanguinating Ammunition (Major)',12,360,0]);

	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1956','Addiction Suppressant (Lesser)',1,2,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=80','Antidote (Lesser)',1,3,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=81','Antiplague (Lesser)',1,3,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=86','Cheetah\'s Elixir (Lesser)',1,3,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1958','Choker-Arm Mutagen (Lesser)',1,3,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1961','Deadweight Mutagen (Lesser)',1,3,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=91','Elixir of Life (Minor)',1,3,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=516','Lastwall Soup',1,3,1]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=95','Leaper\'s Elixir (Lesser)',1,3,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1964','Sanguine Mutagen (Lesser)',1,3,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1968','Theatrical Mutagen (Lesser)',1,3,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=82','Bestial Mutagen (Lesser)',1,4,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=87','Cognitive Mutagen (Lesser)',1,4,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=688','Drakeheart Mutagen (Lesser)',1,4,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=90','Eagle-Eye Elixir (Lesser)',1,4,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1962','Energy Mutagen (Lesser)',1,4,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=94','Juggernaut Mutagen (Lesser)',1,4,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1963','Numbing Tonic (Minor)',1,4,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=97','Quicksilver Mutagen (Lesser)',1,4,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=100','Serene Mutagen (Lesser)',1,4,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=101','Silvertongue Mutagen (Lesser)',1,4,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1969','Vaccine (Minor)',1,4,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=689','Focus Cathartic (Lesser)',2,5,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=691','Sinew-Shock Serum (Lesser)',2,5,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=89','Darkvision Elixir (Lesser)',2,6,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=93','Infiltrator\'s Elixir',2,6,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=84','Bravo\'s Brew (Lesser)',2,7,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=85','Cat\'s Eye Elixir',2,7,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=88','Comprehension Elixir (Lesser)',2,7,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1965','Soothing Tonic (Lesser)',2,7,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1957','Blood Booster (Lesser)',3,9,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=690','Olfactory Obfuscator',3,9,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=82','Bestial Mutagen (Moderate)',3,12,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1958','Choker-Arm Mutagen (Moderate)',3,12,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=87','Cognitive Mutagen (Moderate)',3,12,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1961','Deadweight Mutagen (Moderate)',3,12,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=688','Drakeheart Mutagen (Moderate)',3,12,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1962','Energy Mutagen (Moderate)',3,12,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=94','Juggernaut Mutagen (Moderate)',3,12,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=97','Quicksilver Mutagen (Moderate)',3,12,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1964','Sanguine Mutagen (Moderate)',3,12,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=100','Serene Mutagen (Moderate)',3,12,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=101','Silvertongue Mutagen (Moderate)',3,12,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1966','Spiderfoot Brew (Lesser)',3,12,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1968','Theatrical Mutagen (Moderate)',3,12,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1969','Vaccine (Lesser)',3,12,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=89','Darkvision Elixir (Moderate)',4,11,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=102','Stone Fist Elixir',4,13,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=83','Bomber\'s Eye Elixir (Lesser)',4,14,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=689','Focus Cathartic (Moderate)',4,15,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=98','Salamander Elixir (Lesser)',4,15,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=691','Sinew-Shock Serum (Moderate)',4,15,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=103','Winter Wolf Elixir (Lesser)',4,15,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=96','Mistform Elixir (Lesser)',4,18,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=99','Sea Touch Elixir (Lesser)',5,22,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1967','Stone Body Mutagen (Lesser)',5,22,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=86','Cheetah\'s Elixir (Moderate)',5,25,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=90','Eagle-Eye Elixir (Moderate)',5,27,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1965','Soothing Tonic (Moderate)',5,28,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1960','Contagion Metabolizer (Lesser)',5,30,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=91','Elixir of Life (Lesser)',5,30,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1963','Numbing Tonic (Lesser)',5,30,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1956','Addiction Suppressant (Moderate)',6,30,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=80','Antidote (Moderate)',6,35,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=81','Antiplague (Moderate)',6,35,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1969','Vaccine (Moderate)',6,50,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=96','Mistform Elixir (Moderate)',6,56,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=88','Comprehension Elixir (Greater)',7,54,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=95','Leaper\'s Elixir (Greater)',7,55,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=89','Darkvision Elixir (Greater)',8,90,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=86','Cheetah\'s Elixir (Greater)',9,110,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1959','Chromatic Jellyfish Oil (Lesser)',9,120,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=91','Elixir of Life (Moderate)',9,150,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1963','Numbing Tonic (Moderate)',9,150,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1966','Spiderfoot Brew (Moderate)',9,150,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1956','Addiction Suppressant (Greater)',10,140,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=84','Bravo\'s Brew (Moderate)',10,150,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=80','Antidote (Greater)',10,160,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=81','Antiplague (Greater)',10,160,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=96','Mistform Elixir (Greater)',10,180,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1965','Soothing Tonic (Greater)',10,185,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=90','Eagle-Eye Elixir (Greater)',10,200,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=690','Olfactory Obfuscator (Greater)',10,225,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1957','Blood Booster (Moderate)',11,225,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=82','Bestial Mutagen (Greater)',11,300,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1958','Choker-Arm Mutagen (Greater)',11,300,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=87','Cognitive Mutagen (Greater)',11,300,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1960','Contagion Metabolizer (Moderate)',11,300,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1961','Deadweight Mutagen (Greater)',11,300,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=688','Drakeheart Mutagen (Greater)',11,300,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1962','Energy Mutagen (Greater)',11,300,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=94','Juggernaut Mutagen (Greater)',11,300,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=97','Quicksilver Mutagen (Greater)',11,300,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1964','Sanguine Mutagen (Greater)',11,300,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=100','Serene Mutagen (Greater)',11,300,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=101','Silvertongue Mutagen (Greater)',11,300,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1968','Theatrical Mutagen (Greater)',11,300,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=99','Sea Touch Elixir (Moderate)',12,300,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1967','Stone Body Mutagen (Moderate)',12,300,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=98','Salamander Elixir (Moderate)',12,320,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=103','Winter Wolf Elixir (Moderate)',12,320,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=689','Focus Cathartic (Greater)',12,325,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=691','Sinew-Shock Serum (Greater)',12,325,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1969','Vaccine (Greater)',12,400,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=91','Elixir of Life (Greater)',13,600,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1963','Numbing Tonic (Greater)',13,600,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1956','Addiction Suppressant (Major)',14,500,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=80','Antidote (Major)',14,675,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=81','Antiplague (Major)',14,675,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=83','Bomber\'s Eye Elixir (Greater)',14,700,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1959','Chromatic Jellyfish Oil (Moderate)',14,800,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=84','Bravo\'s Brew (Greater)',15,700,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=99','Sea Touch Elixir (Greater)',15,920,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1967','Stone Body Mutagen (Greater)',15,920,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=91','Elixir of Life (Major)',15,1300,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1963','Numbing Tonic (Major)',16,1400,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=98','Salamander Elixir (Greater)',16,1400,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=103','Winter Wolf Elixir (Greater)',16,1400,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=90','Eagle-Eye Elixir (Major)',16,2000,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1966','Spiderfoot Brew (Greater)',17,2500,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1965','Soothing Tonic (Major)',17,2700,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=82','Bestial Mutagen (Major)',17,3000,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1958','Choker-Arm Mutagen (Major)',17,3000,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=87','Cognitive Mutagen (Major)',17,3000,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1961','Deadweight Mutagen (Major)',17,3000,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=688','Drakeheart Mutagen (Major)',17,3000,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1962','Energy Mutagen (Major)',17,3000,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=94','Juggernaut Mutagen (Major)',17,3000,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=97','Quicksilver Mutagen (Major)',17,3000,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1964','Sanguine Mutagen (Major)',17,3000,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=100','Serene Mutagen (Major)',17,3000,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=101','Silvertongue Mutagen (Major)',17,3000,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1968','Theatrical Mutagen (Major)',17,3000,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=689','Focus Cathartic (Major)',18,3250,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=691','Sinew-Shock Serum (Major)',18,3250,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1957','Blood Booster (Greater)',18,3400,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1969','Vaccine (Major)',18,5000,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1959','Chromatic Jellyfish Oil (Greater)',19,5200,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1960','Contagion Metabolizer (Greater)',19,8000,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=91','Elixir of Life (True)',19,8000,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1963','Numbing Tonic (True)',19,8000,0]);

	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1661','Lady\'s Blessing Oil',1,3,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1660','Drowsy Sun Eye Drops',3,9,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1662','Toothwort Extract',3,9,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1658','Artevil Suspension',3,11,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1663','Yarrow-Root Bandage',4,12,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1659','Curled Cure Gel',7,60,0]);

	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=135','Smokestick (Lesser)',1,3,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=136','Snake Oil',1,2,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=137','Sunrod',1,3,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=138','Tindertwig',1,2,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=695','Forensic Dye',1,3,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=696','Ghost Ink',1,3,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=800','Blindpepper Tube',1,3,1]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=844','Bookthief Brew',1,3,1]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1339','Popdust',1,1,1]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1580','Alchemical Fuse',1,3,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1626','Self-Immolating Note',1,3,1]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1936','Animal Repellent (Minor)',1,3,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1946','Sparkler',1,4,1]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=134','Silversheen',2,6,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=694','Bloodhound Mask (Lesser)',2,6,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=697','Origin Unguent',2,6,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=765','Lovers\' Ink',2,5,2]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1310','Dragon\'s Blood Pudding (Lesser)',2,5,1]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1341','Sneezing Powder',2,7,1]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1516','Quickmelt Slick (Lesser)',2,5,1]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1624','Moonlit Ink',2,5,1]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1939','Emetic Paste (Lesser)',2,5,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=786','Swamp Lily Quilt',3,12,2]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=805','Aurifying Salts',3,12,1]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=848','Quickpatch Glue',3,10,1]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=853','Metalmist Sphere (Lesser)',3,11,1]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=860','Vermin Repellent Agent (Lesser)',3,8,1]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=861','Cold Iron Blanch (Lesser)',3,10,1]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1312','Impossible Cake',3,5,1]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1937','Camouflage Dye (Lesser)',3,10,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1938','Colorful Coating (Blue)',3,8,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1938','Colorful Coating (Green)',3,10,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1938','Colorful Coating (Indigo)',3,10,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1938','Colorful Coating (Orange)',3,12,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1938','Colorful Coating (Red)',3,10,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1938','Colorful Coating (Yellow)',3,8,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1943','Revealing Mist (Lesser)',3,9,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=700','Timeless Salts',4,14,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1516','Quickmelt Slick (Moderate)',4,13,1]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1936','Animal Repellent (Lesser)',4,15,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1938','Colorful Coating (Violet)',4,15,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1941','Healing Vapor (Lesser)',4,20,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=701','Universal Solvent (Moderate)',5,21,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1310','Dragon\'s Blood Pudding (Moderate)',5,25,1]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1945','Soothing Powder (Lesser)',5,30,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=694','Bloodhound Mask (Moderate)',6,40,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1940','Gearbinder Oil (Lesser)',6,45,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1942','Implosion Dust (Lesser)',6,40,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1944','Sense-Dulling Hood (Lesser)',6,40,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=135','Smokestick (Greater)',7,53,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=698','Skinstitch Salve',7,55,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=699','Sovereign Glue',7,55,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1259','Cold Comfort (Lesser)',7,70,1]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1311','Fire and Iceberg',7,60,1]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1937','Camouflage Dye (Greater)',7,60,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1943','Revealing Mist (Greater)',7,60,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=853','Metalmist Sphere (Moderate)',8,90,1]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=860','Vermin Repellent Agent (Moderate)',8,75,1]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1936','Animal Repellent (Moderate)',8,75,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1941','Healing Vapor (Moderate)',8,100,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=840','Body Recovery Kit',9,101,1]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=861','Cold Iron Blanch (Moderate)',9,140,1]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1309','Brewer\'s Regret',9,120,1]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1312','Impossible Cake (Greater)',9,25,1]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1939','Emetic Paste (Moderate)',9,120,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=694','Bloodhound Mask (Greater)',11,250,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1579','Pyronite',11,250,2]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1945','Soothing Powder (Greater)',11,210,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=701','Universal Solvent (Greater)',12,325,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=860','Vermin Repellent Agent (Greater)',12,315,1]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1311','Fire and Iceberg (greater)',12,350,1]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1516','Quickmelt Slick (Greater)',12,310,1]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1936','Animal Repellent (Greater)',12,350,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1940','Gearbinder Oil (Moderate)',12,390,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1941','Healing Vapor (Greater)',12,400,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1942','Implosion Dust (Moderate)',12,370,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1944','Sense-Dulling Hood (Greater)',12,350,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=853','Metalmist Sphere (Greater)',13,500,1]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1310','Dragon\'s Blood Pudding (Greater)',13,425,1]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1309','Brewer\'s Regret (Greater)',14,625,1]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1939','Emetic Paste (Greater)',14,700,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1259','Cold Comfort (Greater)',15,1300,1]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=860','Vermin Repellent Agent (Major)',16,1350,1]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=861','Cold Iron Blanch (Greater)',16,1700,1]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1936','Animal Repellent (Major)',16,1600,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1311','Fire and Iceberg (Major)',17,2500,1]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1312','Impossible Cake (Major)',17,2500,1]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1941','Healing Vapor (Major)',17,3000,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=701','Universal Solvent (Major)',18,3250,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=763','Sun Orchid Poultice',18,5000,2]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1940','Gearbinder Oil (Greater)',18,4500,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1942','Implosion Dust (Greater)',18,4100,0]);
	whiteAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1310','Dragon\'s Blood Pudding (Major)',19,5500,1]);

	return whiteAlchemy;
}

function createBlackAlchemy(){
	var blackAlchemy = [];

	//0: link
	//1: name
	//2: level
	//3: price
	//4: rarity

	//blackAlchemy.push([link,name,level,price,rarity]);

	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=74','Acid Flask (Lesser)',1,3,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=75','Alchemist\'s Fire (Lesser)',1,3,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=684','Blight Bomb (Lesser)',1,3,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=76','Bottled Lightning (Lesser)',1,3,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=686','Dread Ampoule (Lesser)',1,3,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=77','Frost Vial (Lesser)',1,3,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=687','Ghost Charge (Lesser)',1,3,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=78','Tanglefoot Bag (Lesser)',1,3,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=79','Thunderstone (Lesser)',1,3,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1906','Skunk Bomb (Lesser)',1,4,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1257','Sulfur Bomb (Lesser)',1,4,1]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1278','Vexing Vapor (Lesser)',1,4,1]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=74','Acid Flask (Moderate)',3,10,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=75','Alchemist\'s Fire (Moderate)',3,10,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=684','Blight Bomb (Moderate)',3,10,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=76','Bottled Lightning (Moderate)',3,10,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=686','Dread Ampoule (Moderate)',3,10,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=77','Frost Vial (Moderate)',3,10,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=687','Ghost Charge (Moderate)',3,10,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=78','Tanglefoot Bag (Moderate)',3,10,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=79','Thunderstone (Moderate)',3,10,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1906','Skunk Bomb (Moderate)',3,12,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1257','Sulfur Bomb (Moderate)',3,12,1]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1278','Vexing Vapor (Moderate)',3,12,1]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=685','Crystal Shards (Moderate)',4,16,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1906','Skunk Bomb (Greater)',11,240,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1906','Acid Flask (Greater)',11,250,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=75','Alchemist\'s Fire (Greater)',11,250,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=684','Blight Bomb (Greater)',11,250,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=76','Bottled Lightning (Greater)',11,250,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=77','Frost Vial (Greater)',11,250,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=687','Ghost Charge (Greater)',11,250,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=78','Tanglefoot Bag (Greater)',11,250,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=79','Thunderstone (Greater)',11,250,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1257','Sulfur Bomb (Greater)',11,275,1]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=686','Dread Ampoule (Greater)',11,300,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1278','Vexing Vapor (Greater)',11,300,1]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=685','Crystal Shards (Greater)',12,350,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1903','Boulder Seed',12,360,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1907','Trueshape Bomb',12,375,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1905','Shatterstone',12,380,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1904','Lodestone Bomb',12,400,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1902','Blightburn Bomb',15,1200,1]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1906','Skunk Bomb (Major)',17,2400,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=74','Acid Flask (Major)',17,2500,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=75','Alchemist\'s Fire (Major)',17,2500,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=684','Blight Bomb (Major)',17,2500,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=76','Bottled Lightning (Major)',17,2500,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=77','Frost Vial (Major)',17,2500,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=687','Ghost Charge (Major)',17,2500,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=78','Tanglefoot Bag (Major)',17,2500,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=79','Thunderstone (Major)',17,2500,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1257','Sulfur Bomb (Major)',17,2750,1]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=686','Dread Ampoule (Major)',17,3000,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1278','Vexing Vapor (Major)',17,3000,1]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1903','Boulder Seed (Greater)',18,3600,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1907','Trueshape Bomb (Greater)',18,3750,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1905','Shatterstone (Greater)',18,3800,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=685','Crystal Shards (Major)',18,4000,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1904','Lodestone Bomb (Greater)',18,4500,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1902','Blightburn Bomb (Greater)',20,12000,1]);

	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=104','Arsenic',1,3,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=2015','Spear Frog Poison',1,3,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=113','Giant Centipede Venom',1,4,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=105','Belladonna',2,5,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1714','False Flayleaf',2,5,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=106','Black Adder Venom',2,6,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=2007','Looter\'s Lethargy',2,6,1]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=120','Lethargy Poison',2,7,1]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1992','Blue Dragonfly Poison',3,7,1]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=110','Cytillesh Oil',3,10,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=116','Graveroot',3,10,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1277','Toadskin Salve',3,10,1]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=2019','Violet Venom',3,12,1]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=693','Leadenleg',4,15,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1994','Brightshade',4,18,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=2017','Taster\'s Folly',4,20,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1997','Clown Monarch',5,21,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=118','Hunting Spider Venom',5,25,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=2008','Mustard Powder',5,25,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=114','Giant Scorpion Venom',6,40,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1989','Antipode Oil',6,45,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=2016','Stupor Poison',7,16,1]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=115','Giant Wasp Venom',7,55,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=122','Malyass Root Paste',7,55,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1277','Toadskin Salve (Greater)',7,55,1]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=2014','Smother Shroud',7,60,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=124','Nettleweed Residue',8,75,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=2012','Scarlet Mist',8,80,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=132','Wyvern Poison',8,80,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=2020','Warpwobble Poison',8,90,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1999','Curare',8,100,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=121','Lich Dust',9,110,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=129','Spider Root',9,110,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=2013','Sight-Theft Grit',9,115,1]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1995','Careless Delight',9,130,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1407','Abysium Powder',9,150,2]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=131','Wolfsbane',10,155,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=127','Shadow Essence',10,160,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=108','Blightburn Resin',11,225,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1277','Toadskin Salve (Major)',11,225,1]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=2005','Hunger Oil',11,235,1]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=2000','Dancing Lamentation',11,240,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1991','Blisterwort',11,280,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=128','Slumber Wine',12,325,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1998','Clubhead Poison',12,340,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1990','Astringent Venom',12,350,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=111','Deathcap Powder',13,450,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=2004','Gorgon\'s Breath',13,475,1]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=126','Purple Worm Venom',13,500,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=2011','Pummel-Growth Toxin',13,550,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=2001','Death Knell Powder',14,325,1]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=2006','Liar\'s Demise',14,650,1]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=2018','Unending Itch',14,700,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=112','Dragon Bile',15,925,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=123','Mindfog Mist',15,1000,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=2002','Eldritch Flare',15,1100,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=125','Nightmare Vapor',16,1400,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=692','Cerulean Scourge',16,1450,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=109','Brimstone Fumes',16,1500,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=117','Hemlock',17,2250,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=2003','False Hope',17,2600,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1993','Breathtaking Vapor',17,3000,1]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=119','King\'s Sleep',18,4000,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1996','Choleric Contagion',18,4200,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=2010','Pale Fade',19,6000,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=107','Black Lotus Extract',19,6500,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=130','Tears of Death',20,12000,0]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=1988','Achaekek\'s Kiss',20,13000,2]);
	blackAlchemy.push(['https://2e.aonprd.com/Equipment.aspx?ID=2009','Nightmare Salt',20,14000,2]);

	return blackAlchemy;
}

function createDrugs(){
	var drugs = [];

	//0: link
	//1: name
	//2: level
	//3: price
	//4: rarity

	//drugs.push([link,name,level,price,rarity]);

	drugs.push(['https://2e.aonprd.com/Equipment.aspx?ID=623','Methamphetamine (Bloodeye Coffee)',0,5,0]);
	drugs.push(['https://2e.aonprd.com/Equipment.aspx?ID=624','Marijuana (Flayleaf)',0,1,0]);
	drugs.push(['https://2e.aonprd.com/Equipment.aspx?ID=626','Psilocybe Mushroom (Refined Pesh)',1,2,0]);
	drugs.push(['https://2e.aonprd.com/Equipment.aspx?ID=625','Cocaine (Blood Sap)',1,4,0]);
	drugs.push(['https://2e.aonprd.com/Equipment.aspx?ID=627','Heroin (Shiver)',3,10,0]);
	drugs.push(['https://2e.aonprd.com/Equipment.aspx?ID=629','Zerk',4,20,0]);
	drugs.push(['https://2e.aonprd.com/Equipment.aspx?ID=631','Absinthe (Elven Absinthe)',5,25,0]);
	drugs.push(['https://2e.aonprd.com/Equipment.aspx?ID=630','Opium (Cytillesh)',5,30,1]);
	drugs.push(['https://2e.aonprd.com/Equipment.aspx?ID=632','Scour',8,80,1]);
	drugs.push(['https://elb-dev.github.io/javascript-dnd-npc-gen/homebrew/homm-flower.html','Homm Flower',10,300,2]);

	return drugs;
}