function createSpells(){
	var spells = [[],[],[],[],[],[],[],[],[],[]];

	//An individual spell is a three index array.
	//[0] = link to spell on DnD Beyond
	//[1] = spell name
	//[2] = Source
	//Sources:
	//0 = Basic Rules
	//1 = Player's Hand Book
	//2 = Unearthed Arcana
	//3 = Guildmaster's Guide to Ravnica
	//4 = Sword Coast Adventurer's Guide
	//5 = Xanathar's Guide to Everything

	//spells[].push(['','',]);

	//Basic Rules
	spells[2].push(['https://www.dndbeyond.com/spells/acid-arrow','Acid Arrow',0]);
	spells[0].push(['https://www.dndbeyond.com/spells/acid-splash','Acid Splash',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/aid','Aid',0]);
	spells[1].push(['https://www.dndbeyond.com/spells/alarm','Alarm',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/alter-self','Alter Self',0]);
	spells[1].push(['https://www.dndbeyond.com/spells/animal-friendship','Animal Friendship',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/animal-messenger','Animal Messenger',0]);
	spells[8].push(['https://www.dndbeyond.com/spells/animal-shapes','Animal Shapes',0]);
	spells[3].push(['https://www.dndbeyond.com/spells/animate-dead','Animate Dead',0]);
	spells[5].push(['https://www.dndbeyond.com/spells/animate-objects','Animate Objects',0]);
	spells[5].push(['https://www.dndbeyond.com/spells/antilife-shell','Antilife Shell',0]);
	spells[8].push(['https://www.dndbeyond.com/spells/antimagic-field','Antimagic Field',0]);
	spells[8].push(['https://www.dndbeyond.com/spells/antipathy-sympathy','Antipathy/Sympathy',0]);
	spells[4].push(['https://www.dndbeyond.com/spells/arcane-eye','Arcane Eye',0]);
	spells[5].push(['https://www.dndbeyond.com/spells/arcane-hand','Arcane Hand',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/arcane-lock','Arcane Lock',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/arcanists-magic-aura','Arcanist\'s Magic Aura',0]);
	spells[9].push(['https://www.dndbeyond.com/spells/astral-projection','Astral Projection',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/augury','Augury',0]);
	spells[5].push(['https://www.dndbeyond.com/spells/awaken','Awaken',0]);
	spells[1].push(['https://www.dndbeyond.com/spells/bane','Bane',0]);
	spells[4].push(['https://www.dndbeyond.com/spells/banishment','Banishment',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/barkskin','Barkskin',0]);
	spells[3].push(['https://www.dndbeyond.com/spells/beacon-of-hope','Beacon of Hope',0]);
	spells[3].push(['https://www.dndbeyond.com/spells/bestow-curse','Bestow Curse',0]);
	spells[4].push(['https://www.dndbeyond.com/spells/black-tentacles','Black Tentacles',0]);
	spells[6].push(['https://www.dndbeyond.com/spells/blade-barrier','Blade Barrier',0]);
	spells[1].push(['https://www.dndbeyond.com/spells/bless','Bless',0]);
	spells[4].push(['https://www.dndbeyond.com/spells/blight','Blight',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/blindness-deafness','Blindness/Deafness',0]);
	spells[3].push(['https://www.dndbeyond.com/spells/blink','Blink',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/blur','Blur',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/branding-smite','Branding Smite',0]);
	spells[1].push(['https://www.dndbeyond.com/spells/burning-hands','Burning Hands',0]);
	spells[3].push(['https://www.dndbeyond.com/spells/call-lightning','Call Lightning',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/calm-emotions','Calm Emotions',0]);
	spells[6].push(['https://www.dndbeyond.com/spells/chain-lightning','Chain Lightning',0]);
	spells[1].push(['https://www.dndbeyond.com/spells/charm-person','Charm Person',0]);
	spells[0].push(['https://www.dndbeyond.com/spells/chill-touch','Chill Touch',0]);
	spells[6].push(['https://www.dndbeyond.com/spells/circle-of-death','Circle of Death',0]);
	spells[3].push(['https://www.dndbeyond.com/spells/clairvoyance','Clairvoyance',0]);
	spells[8].push(['https://www.dndbeyond.com/spells/clone','Clone',0]);
	spells[5].push(['https://www.dndbeyond.com/spells/cloudkill','Cloudkill',0]);
	spells[1].push(['https://www.dndbeyond.com/spells/color-spray','Color Spray',0]);
	spells[1].push(['https://www.dndbeyond.com/spells/command','Command',0]);
	spells[5].push(['https://www.dndbeyond.com/spells/commune','Commune',0]);
	spells[5].push(['https://www.dndbeyond.com/spells/commune-with-nature','Commune with Nature',0]);
	spells[1].push(['https://www.dndbeyond.com/spells/comprehend-languages','Comprehend Languages',0]);
	spells[4].push(['https://www.dndbeyond.com/spells/compulsion','Compulsion',0]);
	spells[5].push(['https://www.dndbeyond.com/spells/cone-of-cold','Cone of Cold',0]);
	spells[4].push(['https://www.dndbeyond.com/spells/confusion','Confusion',0]);
	spells[3].push(['https://www.dndbeyond.com/spells/conjure-animals','Conjure Animals',0]);
	spells[7].push(['https://www.dndbeyond.com/spells/conjure-celestial','Conjure Celestial',0]);
	spells[5].push(['https://www.dndbeyond.com/spells/conjure-elemental','Conjure Elemental',0]);
	spells[6].push(['https://www.dndbeyond.com/spells/conjure-fey','Conjure Fey',0]);
	spells[4].push(['https://www.dndbeyond.com/spells/conjure-minor-elementals','Conjure Minor Elementals',0]);
	spells[4].push(['https://www.dndbeyond.com/spells/conjure-woodland-beings','Conjure Woodland Beings',0]);
	spells[5].push(['https://www.dndbeyond.com/spells/contact-other-plane','Contact Other Plane',0]);
	spells[5].push(['https://www.dndbeyond.com/spells/contagion','Contagion',0]);
	spells[6].push(['https://www.dndbeyond.com/spells/contingency','Contingency',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/continual-flame','Continual Flame',0]);
	spells[4].push(['https://www.dndbeyond.com/spells/control-water','Control Water',0]);
	spells[8].push(['https://www.dndbeyond.com/spells/control-weather','Control Weather',0]);
	spells[3].push(['https://www.dndbeyond.com/spells/counterspell','Counterspell',0]);
	spells[3].push(['https://www.dndbeyond.com/spells/create-food-and-water','Create Food and Water',0]);
	spells[1].push(['https://www.dndbeyond.com/spells/create-or-destroy-water','Create or Destroy Water',0]);
	spells[6].push(['https://www.dndbeyond.com/spells/create-undead','Create Undead',0]);
	spells[5].push(['https://www.dndbeyond.com/spells/creation','Creation',0]);
	spells[1].push(['https://www.dndbeyond.com/spells/cure-wounds','Cure Wounds',0]);
	spells[0].push(['https://www.dndbeyond.com/spells/dancing-lights','Dancing Lights',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/darkness','Darkness',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/darkvision','Darkvision',0]);
	spells[3].push(['https://www.dndbeyond.com/spells/daylight','Daylight',0]);
	spells[4].push(['https://www.dndbeyond.com/spells/death-ward','Death Ward',0]);
	spells[7].push(['https://www.dndbeyond.com/spells/delayed-blast-fireball','Delayed Blast Fireball',0]);
	spells[8].push(['https://www.dndbeyond.com/spells/demiplane','Demiplane',0]);
	spells[1].push(['https://www.dndbeyond.com/spells/detect-evil-and-good','Detect Evil and Good',0]);
	spells[1].push(['https://www.dndbeyond.com/spells/detect-magic','Detect Magic',0]);
	spells[1].push(['https://www.dndbeyond.com/spells/detect-poison-and-disease','Detect Poison and Disease',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/detect-thoughts','Detect Thoughts',0]);
	spells[4].push(['https://www.dndbeyond.com/spells/dimension-door','Dimension Door',0]);
	spells[1].push(['https://www.dndbeyond.com/spells/disguise-self','Disguise Self',0]);
	spells[6].push(['https://www.dndbeyond.com/spells/disintegrate','Disintegrate',0]);
	spells[5].push(['https://www.dndbeyond.com/spells/dispel-evil-and-good','Dispel Evil and Good',0]);
	spells[3].push(['https://www.dndbeyond.com/spells/dispel-magic','Dispel Magic',0]);
	spells[4].push(['https://www.dndbeyond.com/spells/divination','Divination',0]);
	spells[1].push(['https://www.dndbeyond.com/spells/divine-favor','Divine Favor',0]);
	spells[7].push(['https://www.dndbeyond.com/spells/divine-word','Divine Word',0]);
	spells[4].push(['https://www.dndbeyond.com/spells/dominate-beast','Dominate Beast',0]);
	spells[8].push(['https://www.dndbeyond.com/spells/dominate-monster','Dominate Monster',0]);
	spells[5].push(['https://www.dndbeyond.com/spells/dominate-person','Dominate Person',0]);
	spells[5].push(['https://www.dndbeyond.com/spells/dream','Dream',0]);
	spells[0].push(['https://www.dndbeyond.com/spells/druidcraft','Druidcraft',0]);
	spells[8].push(['https://www.dndbeyond.com/spells/earthquake','Earthquake',0]);
	spells[0].push(['https://www.dndbeyond.com/spells/eldritch-blast','Eldritch Blast',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/enhance-ability','Enhance Ability',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/enlarge-reduce','Enlarge/Reduce',0]);
	spells[1].push(['https://www.dndbeyond.com/spells/entangle','Entangle',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/enthrall','Enthrall',0]);
	spells[7].push(['https://www.dndbeyond.com/spells/etherealness','Etherealness',0]);
	spells[1].push(['https://www.dndbeyond.com/spells/expeditious-retreat','Expeditious Retreat',0]);
	spells[6].push(['https://www.dndbeyond.com/spells/eyebite','Eyebite',0]);
	spells[4].push(['https://www.dndbeyond.com/spells/fabricate','Fabricate',0]);
	spells[1].push(['https://www.dndbeyond.com/spells/faerie-fire','Faerie Fire',0]);
	spells[4].push(['https://www.dndbeyond.com/spells/faithful-hound','Faithful Hound',0]);
	spells[1].push(['https://www.dndbeyond.com/spells/false-life','False Life',0]);
	spells[3].push(['https://www.dndbeyond.com/spells/fear','Fear',0]);
	spells[1].push(['https://www.dndbeyond.com/spells/feather-fall','Feather Fall',0]);
	spells[8].push(['https://www.dndbeyond.com/spells/feeblemind','Feeblemind',0]);
	spells[1].push(['https://www.dndbeyond.com/spells/find-familiar','Find Familiar',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/find-steed','Find Steed',0]);
	spells[6].push(['https://www.dndbeyond.com/spells/find-the-path','Find the Path',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/find-traps','Find Traps',0]);
	spells[7].push(['https://www.dndbeyond.com/spells/finger-of-death','Finger of Death',0]);
	spells[0].push(['https://www.dndbeyond.com/spells/fire-bolt','Fire Bolt',0]);
	spells[4].push(['https://www.dndbeyond.com/spells/fire-shield','Fire Shield',0]);
	spells[7].push(['https://www.dndbeyond.com/spells/fire-storm','Fire Storm',0]);
	spells[3].push(['https://www.dndbeyond.com/spells/fireball','Fireball',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/flame-blade','Flame Blade',0]);
	spells[5].push(['https://www.dndbeyond.com/spells/flame-strike','Flame Strike',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/flaming-sphere','Flaming Sphere',0]);
	spells[6].push(['https://www.dndbeyond.com/spells/flesh-to-stone','Flesh to Stone',0]);
	spells[1].push(['https://www.dndbeyond.com/spells/floating-disk','Floating Disk',0]);
	spells[3].push(['https://www.dndbeyond.com/spells/fly','Fly',0]);
	spells[1].push(['https://www.dndbeyond.com/spells/fog-cloud','Fog Cloud',0]);
	spells[6].push(['https://www.dndbeyond.com/spells/forbiddance','Forbiddance',0]);
	spells[7].push(['https://www.dndbeyond.com/spells/forcecage','Forcecage',0]);
	spells[9].push(['https://www.dndbeyond.com/spells/foresight','Foresight',0]);
	spells[4].push(['https://www.dndbeyond.com/spells/freedom-of-movement','Freedom of Movement',0]);
	spells[6].push(['https://www.dndbeyond.com/spells/freezing-sphere','Freezing Sphere',0]);
	spells[3].push(['https://www.dndbeyond.com/spells/gaseous-form','Gaseous Form',0]);
	spells[9].push(['https://www.dndbeyond.com/spells/gate','Gate',0]);
	spells[5].push(['https://www.dndbeyond.com/spells/geas','Geas',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/gentle-repose','Gentle Repose',0]);
	spells[4].push(['https://www.dndbeyond.com/spells/giant-insect','Giant Insect',0]);
	spells[8].push(['https://www.dndbeyond.com/spells/glibness','Glibness',0]);
	spells[6].push(['https://www.dndbeyond.com/spells/globe-of-invulnerability','Globe of Invulnerability',0]);
	spells[3].push(['https://www.dndbeyond.com/spells/glyph-of-warding','Glyph of Warding',0]);
	spells[1].push(['https://www.dndbeyond.com/spells/goodberry','Goodberry',0]);
	spells[1].push(['https://www.dndbeyond.com/spells/grease','Grease',0]);
	spells[4].push(['https://www.dndbeyond.com/spells/greater-invisibility','Greater Invisibility',0]);
	spells[5].push(['https://www.dndbeyond.com/spells/greater-restoration','Greater Restoration',0]);
	spells[4].push(['https://www.dndbeyond.com/spells/guardian-of-faith','Guardian of Faith',0]);
	spells[6].push(['https://www.dndbeyond.com/spells/guards-and-wards','Guards and Wards',0]);
	spells[0].push(['https://www.dndbeyond.com/spells/guidance','Guidance',0]);
	spells[1].push(['https://www.dndbeyond.com/spells/guiding-bolt','Guiding Bolt',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/gust-of-wind','Gust of Wind',0]);
	spells[5].push(['https://www.dndbeyond.com/spells/hallow','Hallow',0]);
	spells[4].push(['https://www.dndbeyond.com/spells/hallucinatory-terrain','Hallucinatory Terrain',0]);
	spells[6].push(['https://www.dndbeyond.com/spells/harm','Harm',0]);
	spells[3].push(['https://www.dndbeyond.com/spells/haste','Haste',0]);
	spells[6].push(['https://www.dndbeyond.com/spells/heal','Heal',0]);
	spells[1].push(['https://www.dndbeyond.com/spells/healing-word','Healing Word',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/heat-metal','Heat Metal',0]);
	spells[1].push(['https://www.dndbeyond.com/spells/hellish-rebuke','Hellish Rebuke',0]);
	spells[6].push(['https://www.dndbeyond.com/spells/heroes-feast','Heroes\' Feast',0]);
	spells[1].push(['https://www.dndbeyond.com/spells/heroism','Heroism',0]);
	spells[1].push(['https://www.dndbeyond.com/spells/hideous-laughter','Hideous Laughter',0]);
	spells[5].push(['https://www.dndbeyond.com/spells/hold-monster','Hold Monster',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/hold-person','Hold Person',0]);
	spells[8].push(['https://www.dndbeyond.com/spells/holy-aura','Holy Aura',0]);
	spells[1].push(['https://www.dndbeyond.com/spells/hunters-mark','Hunter\'s Mark',0]);
	spells[3].push(['https://www.dndbeyond.com/spells/hypnotic-pattern','Hypnotic Pattern',0]);
	spells[4].push(['https://www.dndbeyond.com/spells/ice-storm','Ice Storm',0]);
	spells[1].push(['https://www.dndbeyond.com/spells/identify','Identify',0]);
	spells[1].push(['https://www.dndbeyond.com/spells/illusory-script','Illusory Script',0]);
	spells[9].push(['https://www.dndbeyond.com/spells/imprisonment','Imprisonment',0]);
	spells[8].push(['https://www.dndbeyond.com/spells/incendiary-cloud','Incendiary Cloud',0]);
	spells[1].push(['https://www.dndbeyond.com/spells/inflict-wounds','Inflict Wounds',0]);
	spells[5].push(['https://www.dndbeyond.com/spells/insect-plague','Insect Plague',0]);
	spells[6].push(['https://www.dndbeyond.com/spells/instant-summons','Instant Summons',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/invisibility','Invisibility',0]);
	spells[1].push(['https://www.dndbeyond.com/spells/jump','Jump',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/knock','Knock',0]);
	spells[5].push(['https://www.dndbeyond.com/spells/legend-lore','Legend Lore',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/lesser-restoration','Lesser Restoration',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/levitate','Levitate',0]);
	spells[0].push(['https://www.dndbeyond.com/spells/light','Light',0]);
	spells[3].push(['https://www.dndbeyond.com/spells/lightning-bolt','Lightning Bolt',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/locate-animals-or-plants','Locate Animals or Plants',0]);
	spells[4].push(['https://www.dndbeyond.com/spells/locate-creature','Locate Creature',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/locate-object','Locate Object',0]);
	spells[1].push(['https://www.dndbeyond.com/spells/longstrider','Longstrider',0]);
	spells[1].push(['https://www.dndbeyond.com/spells/mage-armor','Mage Armor',0]);
	spells[0].push(['https://www.dndbeyond.com/spells/mage-hand','Mage Hand',0]);
	spells[3].push(['https://www.dndbeyond.com/spells/magic-circle','Magic Circle',0]);
	spells[6].push(['https://www.dndbeyond.com/spells/magic-jar','Magic Jar',0]);
	spells[1].push(['https://www.dndbeyond.com/spells/magic-missile','Magic Missile',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/magic-mouth','Magic Mouth',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/magic-weapon','Magic Weapon',0]);
	spells[7].push(['https://www.dndbeyond.com/spells/magnificent-mansion','Magnificent Mansion',0]);
	spells[3].push(['https://www.dndbeyond.com/spells/major-image','Major Image',0]);
	spells[5].push(['https://www.dndbeyond.com/spells/mass-cure-wounds','Mass Cure Wounds',0]);
	spells[9].push(['https://www.dndbeyond.com/spells/mass-heal','Mass Heal',0]);
	spells[3].push(['https://www.dndbeyond.com/spells/mass-healing-word','Mass Healing Word',0]);
	spells[6].push(['https://www.dndbeyond.com/spells/mass-suggestion','Mass Suggestion',0]);
	spells[8].push(['https://www.dndbeyond.com/spells/maze','Maze',0]);
	spells[3].push(['https://www.dndbeyond.com/spells/meld-into-stone','Meld into Stone',0]);
	spells[0].push(['https://www.dndbeyond.com/spells/mending','Mending',0]);
	spells[0].push(['https://www.dndbeyond.com/spells/message','Message',0]);
	spells[9].push(['https://www.dndbeyond.com/spells/meteor-swarm','Meteor Swarm',0]);
	spells[8].push(['https://www.dndbeyond.com/spells/mind-blank','Mind Blank',0]);
	spells[0].push(['https://www.dndbeyond.com/spells/minor-illusion','Minor Illusion',0]);
	spells[7].push(['https://www.dndbeyond.com/spells/mirage-arcane','Mirage Arcane',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/mirror-image','Mirror Image',0]);
	spells[5].push(['https://www.dndbeyond.com/spells/mislead','Mislead',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/misty-step','Misty Step',0]);
	spells[5].push(['https://www.dndbeyond.com/spells/modify-memory','Modify Memory',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/moonbeam','Moonbeam',0]);
	spells[7].push(['https://www.dndbeyond.com/spells/mordenkainens-sword','Mordenkainen’s Sword',0]);
	spells[6].push(['https://www.dndbeyond.com/spells/move-earth','Move Earth',0]);
	spells[3].push(['https://www.dndbeyond.com/spells/nondetection','Nondetection',0]);
	spells[6].push(['https://www.dndbeyond.com/spells/ottos-irresistible-dance','Otto\'s Irresistible Dance',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/pass-without-trace','Pass without Trace',0]);
	spells[5].push(['https://www.dndbeyond.com/spells/passwall','Passwall',0]);
	spells[4].push(['https://www.dndbeyond.com/spells/phantasmal-killer','Phantasmal Killer',0]);
	spells[3].push(['https://www.dndbeyond.com/spells/phantom-steed','Phantom Steed',0]);
	spells[6].push(['https://www.dndbeyond.com/spells/planar-ally','Planar Ally',0]);
	spells[5].push(['https://www.dndbeyond.com/spells/planar-binding','Planar Binding',0]);
	spells[7].push(['https://www.dndbeyond.com/spells/plane-shift','Plane Shift',0]);
	spells[3].push(['https://www.dndbeyond.com/spells/plant-growth','Plant Growth',0]);
	spells[0].push(['https://www.dndbeyond.com/spells/poison-spray','Poison Spray',0]);
	spells[4].push(['https://www.dndbeyond.com/spells/polymorph','Polymorph',0]);
	spells[9].push(['https://www.dndbeyond.com/spells/power-word-kill','Power Word Kill',0]);
	spells[8].push(['https://www.dndbeyond.com/spells/power-word-stun','Power Word Stun',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/prayer-of-healing','Prayer of Healing',0]);
	spells[0].push(['https://www.dndbeyond.com/spells/prestidigitation','Prestidigitation',0]);
	spells[7].push(['https://www.dndbeyond.com/spells/prismatic-spray','Prismatic Spray',0]);
	spells[9].push(['https://www.dndbeyond.com/spells/prismatic-wall','Prismatic Wall',0]);
	spells[4].push(['https://www.dndbeyond.com/spells/private-sanctum','Private Sanctum',0]);
	spells[0].push(['https://www.dndbeyond.com/spells/produce-flame','Produce Flame',0]);
	spells[6].push(['https://www.dndbeyond.com/spells/programmed-illusion','Programmed Illusion',0]);
	spells[7].push(['https://www.dndbeyond.com/spells/project-image','Project Image',0]);
	spells[3].push(['https://www.dndbeyond.com/spells/protection-from-energy','Protection from Energy',0]);
	spells[1].push(['https://www.dndbeyond.com/spells/protection-from-evil-and-good','Protection from Evil and Good',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/protection-from-poison','Protection from Poison',0]);
	spells[1].push(['https://www.dndbeyond.com/spells/purify-food-and-drink','Purify Food and Drink',0]);
	spells[5].push(['https://www.dndbeyond.com/spells/raise-dead','Raise Dead',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/ray-of-enfeeblement','Ray of Enfeeblement',0]);
	spells[0].push(['https://www.dndbeyond.com/spells/ray-of-frost','Ray of Frost',0]);
	spells[7].push(['https://www.dndbeyond.com/spells/regenerate','Regenerate',0]);
	spells[5].push(['https://www.dndbeyond.com/spells/reincarnate','Reincarnate',0]);
	spells[3].push(['https://www.dndbeyond.com/spells/remove-curse','Remove Curse',0]);
	spells[4].push(['https://www.dndbeyond.com/spells/resilient-sphere','Resilient Sphere',0]);
	spells[0].push(['https://www.dndbeyond.com/spells/resistance','Resistance',0]);
	spells[7].push(['https://www.dndbeyond.com/spells/resurrection','Resurrection',0]);
	spells[7].push(['https://www.dndbeyond.com/spells/reverse-gravity','Reverse Gravity',0]);
	spells[3].push(['https://www.dndbeyond.com/spells/revivify','Revivify',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/rope-trick','Rope Trick',0]);
	spells[0].push(['https://www.dndbeyond.com/spells/sacred-flame','Sacred Flame',0]);
	spells[1].push(['https://www.dndbeyond.com/spells/sanctuary','Sanctuary',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/scorching-ray','Scorching Ray',0]);
	spells[5].push(['https://www.dndbeyond.com/spells/scrying','Scrying',0]);
	spells[4].push(['https://www.dndbeyond.com/spells/secret-chest','Secret Chest',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/see-invisibility','See Invisibility',0]);
	spells[5].push(['https://www.dndbeyond.com/spells/seeming','Seeming',0]);
	spells[3].push(['https://www.dndbeyond.com/spells/sending','Sending',0]);
	spells[7].push(['https://www.dndbeyond.com/spells/sequester','Sequester',0]);
	spells[9].push(['https://www.dndbeyond.com/spells/shapechange','Shapechange',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/shatter','Shatter',0]);
	spells[1].push(['https://www.dndbeyond.com/spells/shield','Shield',0]);
	spells[1].push(['https://www.dndbeyond.com/spells/shield-of-faith','Shield of Faith',0]);
	spells[0].push(['https://www.dndbeyond.com/spells/shillelagh','Shillelagh',0]);
	spells[0].push(['https://www.dndbeyond.com/spells/shocking-grasp','Shocking Grasp',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/silence','Silence',0]);
	spells[1].push(['https://www.dndbeyond.com/spells/silent-image','Silent Image',0]);
	spells[7].push(['https://www.dndbeyond.com/spells/simulacrum','Simulacrum',0]);
	spells[1].push(['https://www.dndbeyond.com/spells/sleep','Sleep',0]);
	spells[3].push(['https://www.dndbeyond.com/spells/sleet-storm','Sleet Storm',0]);
	spells[3].push(['https://www.dndbeyond.com/spells/slow','Slow',0]);
	spells[0].push(['https://www.dndbeyond.com/spells/spare-the-dying','Spare the Dying',0]);
	spells[1].push(['https://www.dndbeyond.com/spells/speak-with-animals','Speak with Animals',0]);
	spells[3].push(['https://www.dndbeyond.com/spells/speak-with-dead','Speak with Dead',0]);
	spells[3].push(['https://www.dndbeyond.com/spells/speak-with-plants','Speak with Plants',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/spider-climb','Spider Climb',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/spike-growth','Spike Growth',0]);
	spells[3].push(['https://www.dndbeyond.com/spells/spirit-guardians','Spirit Guardians',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/spiritual-weapon','Spiritual Weapon',0]);
	spells[3].push(['https://www.dndbeyond.com/spells/stinking-cloud','Stinking Cloud',0]);
	spells[4].push(['https://www.dndbeyond.com/spells/stone-shape','Stone Shape',0]);
	spells[4].push(['https://www.dndbeyond.com/spells/stoneskin','Stoneskin',0]);
	spells[9].push(['https://www.dndbeyond.com/spells/storm-of-vengeance','Storm of Vengeance',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/suggestion','Suggestion',0]);
	spells[6].push(['https://www.dndbeyond.com/spells/sunbeam','Sunbeam',0]);
	spells[8].push(['https://www.dndbeyond.com/spells/sunburst','Sunburst',0]);
	spells[7].push(['https://www.dndbeyond.com/spells/symbol','Symbol',0]);
	spells[5].push(['https://www.dndbeyond.com/spells/telekinesis','Telekinesis',0]);
	spells[5].push(['https://www.dndbeyond.com/spells/telepathic-bond','Telepathic Bond',0]);
	spells[7].push(['https://www.dndbeyond.com/spells/teleport','Teleport',0]);
	spells[5].push(['https://www.dndbeyond.com/spells/teleportation-circle','Teleportation Circle',0]);
	spells[0].push(['https://www.dndbeyond.com/spells/thaumaturgy','Thaumaturgy',0]);
	spells[1].push(['https://www.dndbeyond.com/spells/thunderwave','Thunderwave',0]);
	spells[9].push(['https://www.dndbeyond.com/spells/time-stop','Time Stop',0]);
	spells[3].push(['https://www.dndbeyond.com/spells/tiny-hut','Tiny Hut',0]);
	spells[3].push(['https://www.dndbeyond.com/spells/tongues','Tongues',0]);
	spells[6].push(['https://www.dndbeyond.com/spells/transport-via-plants','Transport via Plants',0]);
	spells[5].push(['https://www.dndbeyond.com/spells/tree-stride','Tree Stride',0]);
	spells[9].push(['https://www.dndbeyond.com/spells/true-polymorph','True Polymorph',0]);
	spells[9].push(['https://www.dndbeyond.com/spells/true-resurrection','True Resurrection',0]);
	spells[6].push(['https://www.dndbeyond.com/spells/true-seeing','True Seeing',0]);
	spells[0].push(['https://www.dndbeyond.com/spells/true-strike','True Strike',0]);
	spells[1].push(['https://www.dndbeyond.com/spells/unseen-servant','Unseen Servant',0]);
	spells[3].push(['https://www.dndbeyond.com/spells/vampiric-touch','Vampiric Touch',0]);
	spells[0].push(['https://www.dndbeyond.com/spells/vicious-mockery','Vicious Mockery',0]);
	spells[4].push(['https://www.dndbeyond.com/spells/wall-of-fire','Wall of Fire',0]);
	spells[5].push(['https://www.dndbeyond.com/spells/wall-of-force','Wall of Force',0]);
	spells[6].push(['https://www.dndbeyond.com/spells/wall-of-ice','Wall of Ice',0]);
	spells[5].push(['https://www.dndbeyond.com/spells/wall-of-stone','Wall of Stone',0]);
	spells[6].push(['https://www.dndbeyond.com/spells/wall-of-thorns','Wall of Thorns',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/warding-bond','Warding Bond',0]);
	spells[3].push(['https://www.dndbeyond.com/spells/water-breathing','Water Breathing',0]);
	spells[3].push(['https://www.dndbeyond.com/spells/water-walk','Water Walk',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/web','Web',0]);
	spells[9].push(['https://www.dndbeyond.com/spells/weird','Weird',0]);
	spells[6].push(['https://www.dndbeyond.com/spells/wind-walk','Wind Walk',0]);
	spells[3].push(['https://www.dndbeyond.com/spells/wind-wall','Wind Wall',0]);
	spells[9].push(['https://www.dndbeyond.com/spells/wish','Wish',0]);
	spells[6].push(['https://www.dndbeyond.com/spells/word-of-recall','Word of Recall',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/zone-of-truth','Zone of Truth',0]);

	//Player Hand Book
	spells[6].push(['https://www.dndbeyond.com/spells/arcane-gate','Arcane Gate',1]);
	spells[1].push(['https://www.dndbeyond.com/spells/armor-of-agathys','Armor of Agathys',1]);
	spells[1].push(['https://www.dndbeyond.com/spells/arms-of-hadar','Arms of Hadar',1]);
	spells[4].push(['https://www.dndbeyond.com/spells/aura-of-life','Aura of Life',1]);
	spells[4].push(['https://www.dndbeyond.com/spells/aura-of-purity','Aura of Purity',1]);
	spells[3].push(['https://www.dndbeyond.com/spells/aura-of-vitality','Aura of Vitality',1]);
	spells[5].push(['https://www.dndbeyond.com/spells/banishing-smite','Banishing Smite',1]);
	spells[2].push(['https://www.dndbeyond.com/spells/beast-sense','Beast Sense',1]);
	spells[5].push(['https://www.dndbeyond.com/spells/bigbys-hand','Bigby\'s Hand',1]);
	spells[0].push(['https://www.dndbeyond.com/spells/blade-ward','Blade Ward',1]);
	spells[3].push(['https://www.dndbeyond.com/spells/blinding-smite','Blinding Smite',1]);
	spells[1].push(['https://www.dndbeyond.com/spells/chromatic-orb','Chromatic Orb',1]);
	spells[5].push(['https://www.dndbeyond.com/spells/circle-of-power','Circle of Power',1]);
	spells[2].push(['https://www.dndbeyond.com/spells/cloud-of-daggers','Cloud of Daggers',1]);
	spells[1].push(['https://www.dndbeyond.com/spells/compelled-duel','Compelled Duel',1]);
	spells[3].push(['https://www.dndbeyond.com/spells/conjure-barrage','Conjure Barrage',1]);
	spells[5].push(['https://www.dndbeyond.com/spells/conjure-volley','Conjure Volley',1]);
	spells[2].push(['https://www.dndbeyond.com/spells/cordon-of-arrows','Cordon of Arrows',1]);
	spells[2].push(['https://www.dndbeyond.com/spells/crown-of-madness','Crown of Madness',1]);
	spells[3].push(['https://www.dndbeyond.com/spells/crusaders-mantle','Crusader’s Mantle',1]);
	spells[5].push(['https://www.dndbeyond.com/spells/destructive-wave','Destructive Wave',1]);
	spells[1].push(['https://www.dndbeyond.com/spells/dissonant-whispers','Dissonant Whispers',1]);
	spells[6].push(['https://www.dndbeyond.com/spells/drawmijs-instant-summons','Drawmij\'s Instant Summons',1]);
	spells[3].push(['https://www.dndbeyond.com/spells/elemental-weapon','Elemental Weapon',1]);
	spells[1].push(['https://www.dndbeyond.com/spells/ensnaring-strike','Ensnaring Strike',1]);
	spells[4].push(['https://www.dndbeyond.com/spells/evards-black-tentacles','Evard’s Black Tentacles',1]);
	spells[3].push(['https://www.dndbeyond.com/spells/feign-death','Feign Death',1]);
	spells[0].push(['https://www.dndbeyond.com/spells/friends','Friends',1]);
	spells[4].push(['https://www.dndbeyond.com/spells/grasping-vine','Grasping Vine',1]);
	spells[1].push(['https://www.dndbeyond.com/spells/hail-of-thorns','Hail of Thorns',1]);
	spells[1].push(['https://www.dndbeyond.com/spells/hex','Hex',1]);
	spells[3].push(['https://www.dndbeyond.com/spells/hunger-of-hadar','Hunger of Hadar',1]);
	spells[4].push(['https://www.dndbeyond.com/spells/leomunds-secret-chest','Leomund’s Secret Chest',1]);
	spells[3].push(['https://www.dndbeyond.com/spells/leomunds-tiny-hut','Leomund’s Tiny Hut',1]);
	spells[3].push(['https://www.dndbeyond.com/spells/lightning-arrow','Lightning Arrow',1]);
	spells[2].push(['https://www.dndbeyond.com/spells/melfs-acid-arrow','Melf’s Acid Arrow',1]);
	spells[4].push(['https://www.dndbeyond.com/spells/mordenkainens-faithful-hound','Mordenkainen’s Faithful Hound',1]);
	spells[4].push(['https://www.dndbeyond.com/spells/mordenkainens-private-sanctum','Mordenkainen’s Private Sanctum',1]);
	spells[7].push(['https://www.dndbeyond.com/spells/mordenkainens-magnificent-mansion','Mordenkainen\'s Magnificent Mansion',1]);
	spells[2].push(['https://www.dndbeyond.com/spells/nystuls-magic-aura','Nystul’s Magic Aura',1]);
	spells[4].push(['https://www.dndbeyond.com/spells/otilukes-resilient-sphere','Otiluke’s Resilient Sphere',1]);
	spells[6].push(['https://www.dndbeyond.com/spells/otilukes-freezing-sphere','Otiluke\'s Freezing Sphere',1]);
	spells[2].push(['https://www.dndbeyond.com/spells/phantasmal-force','Phantasmal Force',1]);
	spells[9].push(['https://www.dndbeyond.com/spells/power-word-heal','Power Word Heal',1]);
	spells[5].push(['https://www.dndbeyond.com/spells/rarys-telepathic-bond','Rary\'s Telepathic Bond',1]);
	spells[1].push(['https://www.dndbeyond.com/spells/ray-of-sickness','Ray of Sickness',1]);
	spells[1].push(['https://www.dndbeyond.com/spells/searing-smite','Searing Smite',1]);
	spells[4].push(['https://www.dndbeyond.com/spells/staggering-smite','Staggering Smite',1]);
	spells[5].push(['https://www.dndbeyond.com/spells/swift-quiver','Swift Quiver',1]);
	spells[1].push(['https://www.dndbeyond.com/spells/tashas-hideous-laughter','Tasha’s Hideous Laughter',1]);
	spells[8].push(['https://www.dndbeyond.com/spells/telepathy','Telepathy',1]);
	spells[1].push(['https://www.dndbeyond.com/spells/tensers-floating-disk','Tenser’s Floating Disk',1]);
	spells[0].push(['https://www.dndbeyond.com/spells/thorn-whip','Thorn Whip',1]);
	spells[1].push(['https://www.dndbeyond.com/spells/thunderous-smite','Thunderous Smite',1]);
	spells[8].push(['https://www.dndbeyond.com/spells/tsunami','Tsunami',1]);
	spells[1].push(['https://www.dndbeyond.com/spells/witch-bolt','Witch Bolt',1]);
	spells[1].push(['https://www.dndbeyond.com/spells/wrathful-smite','Wrathful Smite',1]);

	//Unearthed Arcana
	spells[1].push(['https://www.dndbeyond.com/spells/acid-stream-ua','Acid Stream (UA)',0]);
	spells[4].push(['https://www.dndbeyond.com/spells/intellect-fortress-ua','Intellect Fortress (UA)',0]);
	spells[0].push(['https://www.dndbeyond.com/spells/mind-sliver-ua','Mind Sliver (UA)',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/mind-thrust-ua','Mind Thrust (UA)',0]);
	spells[6].push(['https://www.dndbeyond.com/spells/otherworldly-form-ua','Otherworldly Form (UA)',0]);
	spells[3].push(['https://www.dndbeyond.com/spells/spirit-shroud-ua','Spirit Shroud (UA)',0]);
	spells[4].push(['https://www.dndbeyond.com/spells/summon-aberrant-spirit-ua','Summon Aberrant Spirit (UA)',0]);
	spells[2].push(['https://www.dndbeyond.com/spells/summon-bestial-spirit-ua','Summon Bestial Spirit (UA)',0]);
	spells[5].push(['https://www.dndbeyond.com/spells/summon-celestial-spirit-ua','Summon Celestial Spirit (UA)',0]);
	spells[4].push(['https://www.dndbeyond.com/spells/summon-elemental-spirit-ua','Summon Elemental Spirit (UA)',0]);
	spells[3].push(['https://www.dndbeyond.com/spells/summon-fey-spirit-ua','Summon Fey Spirit (UA)',0]);
	spells[6].push(['https://www.dndbeyond.com/spells/summon-fiendish-spirit-ua','Summon Fiendish Spirit (UA)',0]);
	spells[3].push(['https://www.dndbeyond.com/spells/summon-shadow-spirit-ua','Summon Shadow Spirit (UA)',0]);
	spells[3].push(['https://www.dndbeyond.com/spells/summon-undead-spirit-ua','Summon Undead Spirit (UA)',0]);

	//Guildmasters Guide to Ravnica
	spells[1].push(['https://www.dndbeyond.com/spells/chaos-bolt','Chaos Bolt',3]);
	spells[0].push(['https://www.dndbeyond.com/spells/encode-thoughts','Encode Thoughts',3]);

	//Sword Coast Adventurer's Guide
	spells[0].push(['https://www.dndbeyond.com/spells/booming-blade','Booming Blade',4]);
	spells[0].push(['https://www.dndbeyond.com/spells/green-flame-blade','Green-Flame Blade',4]);
	spells[0].push(['https://www.dndbeyond.com/spells/lightning-lure','Lightning Lure',4]);
	spells[0].push(['https://www.dndbeyond.com/spells/sword-burst','Sword Burst',4]);

	//Xanathar's Guide to Everything
	spells[8].push(['https://www.dndbeyond.com/spells/abi-dalzims-horrid-wilting','Abi-Dalzim’s Horrid Wilting',5]);
	spells[1].push(['https://www.dndbeyond.com/spells/absorb-elements','Absorb Elements',5]);
	spells[2].push(['https://www.dndbeyond.com/spells/aganazzars-scorcher','Aganazzar’s Scorcher',5]);
	spells[1].push(['https://www.dndbeyond.com/spells/beast-bond','Beast Bond',5]);
	spells[6].push(['https://www.dndbeyond.com/spells/bones-of-the-earth','Bones of the Earth',5]);
	spells[1].push(['https://www.dndbeyond.com/spells/catapult','Catapult',5]);
	spells[3].push(['https://www.dndbeyond.com/spells/catnap','Catnap',5]);
	spells[1].push(['https://www.dndbeyond.com/spells/cause-fear','Cause Fear',5]);
	spells[1].push(['https://www.dndbeyond.com/spells/ceremony','Ceremony',5]);
	spells[1].push(['https://www.dndbeyond.com/spells/chaos-bolt','Chaos Bolt',5]);
	spells[4].push(['https://www.dndbeyond.com/spells/charm-monster','Charm Monster',5]);
	spells[0].push(['https://www.dndbeyond.com/spells/control-flames','Control Flames',5]);
	spells[5].push(['https://www.dndbeyond.com/spells/control-winds','Control Winds',5]);
	spells[0].push(['https://www.dndbeyond.com/spells/create-bonfire','Create Bonfire',5]);
	spells[6].push(['https://www.dndbeyond.com/spells/create-homunculus','Create Homunculus',5]);
	spells[7].push(['https://www.dndbeyond.com/spells/crown-of-stars','Crown of Stars',5]);
	spells[5].push(['https://www.dndbeyond.com/spells/danse-macabre','Danse Macabre',5]);
	spells[5].push(['https://www.dndbeyond.com/spells/dawn','Dawn',5]);
	spells[2].push(['https://www.dndbeyond.com/spells/dragons-breath','Dragon\'s Breath',5]);
	spells[6].push(['https://www.dndbeyond.com/spells/druid-grove','Druid Grove',5]);
	spells[2].push(['https://www.dndbeyond.com/spells/dust-devil','Dust Devil',5]);
	spells[1].push(['https://www.dndbeyond.com/spells/earth-tremor','Earth Tremor',5]);
	spells[2].push(['https://www.dndbeyond.com/spells/earthbind','Earthbind',5]);
	spells[4].push(['https://www.dndbeyond.com/spells/elemental-bane','Elemental Bane',5]);
	spells[3].push(['https://www.dndbeyond.com/spells/enemies-abound','Enemies Abound',5]);
	spells[5].push(['https://www.dndbeyond.com/spells/enervation','Enervation',5]);
	spells[3].push(['https://www.dndbeyond.com/spells/erupting-earth','Erupting Earth',5]);
	spells[5].push(['https://www.dndbeyond.com/spells/far-step','Far Step',5]);
	spells[4].push(['https://www.dndbeyond.com/spells/find-greater-steed','Find Greater Steed',5]);
	spells[3].push(['https://www.dndbeyond.com/spells/flame-arrows','Flame Arrows',5]);
	spells[0].push(['https://www.dndbeyond.com/spells/frostbite','Frostbite',5]);
	spells[4].push(['https://www.dndbeyond.com/spells/guardian-of-nature','Guardian of Nature',5]);
	spells[0].push(['https://www.dndbeyond.com/spells/gust','Gust',5]);
	spells[2].push(['https://www.dndbeyond.com/spells/healing-spirit','Healing Spirit',5]);
	spells[5].push(['https://www.dndbeyond.com/spells/holy-weapon','Holy Weapon',5]);
	spells[1].push(['https://www.dndbeyond.com/spells/ice-knife','Ice Knife',5]);
	spells[8].push(['https://www.dndbeyond.com/spells/illusory-dragon','Illusory Dragon',5]);
	spells[5].push(['https://www.dndbeyond.com/spells/immolation','Immolation',5]);
	spells[5].push(['https://www.dndbeyond.com/spells/infernal-calling','Infernal Calling',5]);
	spells[0].push(['https://www.dndbeyond.com/spells/infestation','Infestation',5]);
	spells[6].push(['https://www.dndbeyond.com/spells/investiture-of-flame','Investiture of Flame',5]);
	spells[6].push(['https://www.dndbeyond.com/spells/investiture-of-ice','Investiture of Ice',5]);
	spells[6].push(['https://www.dndbeyond.com/spells/investiture-of-stone','Investiture of Stone',5]);
	spells[6].push(['https://www.dndbeyond.com/spells/investiture-of-wind','Investiture of Wind',5]);
	spells[9].push(['https://www.dndbeyond.com/spells/invulnerability','Invulnerability',5]);
	spells[3].push(['https://www.dndbeyond.com/spells/life-transference','Life Transference',5]);
	spells[8].push(['https://www.dndbeyond.com/spells/maddening-darkness','Maddening Darkness',5]);
	spells[5].push(['https://www.dndbeyond.com/spells/maelstrom','Maelstrom',5]);
	spells[0].push(['https://www.dndbeyond.com/spells/magic-stone','Magic Stone',5]);
	spells[9].push(['https://www.dndbeyond.com/spells/mass-polymorph','Mass Polymorph',5]);
	spells[2].push(['https://www.dndbeyond.com/spells/maximilians-earthen-grasp','Maximilian’s Earthen Grasp',5]);
	spells[3].push(['https://www.dndbeyond.com/spells/melfs-minute-meteors','Melf\'s Minute Meteors',5]);
	spells[6].push(['https://www.dndbeyond.com/spells/mental-prison','Mental Prison',5]);
	spells[8].push(['https://www.dndbeyond.com/spells/mighty-fortress','Mighty Fortress',5]);
	spells[2].push(['https://www.dndbeyond.com/spells/mind-spike','Mind Spike',5]);
	spells[0].push(['https://www.dndbeyond.com/spells/mold-earth','Mold Earth',5]);
	spells[5].push(['https://www.dndbeyond.com/spells/negative-energy-flood','Negative Energy Flood',5]);
	spells[7].push(['https://www.dndbeyond.com/spells/power-word-pain','Power Word Pain',5]);
	spells[0].push(['https://www.dndbeyond.com/spells/primal-savagery','Primal Savagery',5]);
	spells[6].push(['https://www.dndbeyond.com/spells/primordial-ward','Primordial Ward',5]);
	spells[9].push(['https://www.dndbeyond.com/spells/psychic-scream','Psychic Scream',5]);
	spells[2].push(['https://www.dndbeyond.com/spells/pyrotechnics','Pyrotechnics',5]);
	spells[6].push(['https://www.dndbeyond.com/spells/scatter','Scatter',5]);
	spells[2].push(['https://www.dndbeyond.com/spells/shadow-blade','Shadow Blade',5]);
	spells[4].push(['https://www.dndbeyond.com/spells/shadow-of-moil','Shadow of Moil',5]);
	spells[0].push(['https://www.dndbeyond.com/spells/shape-water','Shape Water',5]);
	spells[4].push(['https://www.dndbeyond.com/spells/sickening-radiance','Sickening Radiance',5]);
	spells[5].push(['https://www.dndbeyond.com/spells/skill-empowerment','Skill Empowerment',5]);
	spells[2].push(['https://www.dndbeyond.com/spells/skywrite','Skywrite',5]);
	spells[1].push(['https://www.dndbeyond.com/spells/snare','Snare',5]);
	spells[2].push(['https://www.dndbeyond.com/spells/snillocs-snowball-swarm','Snilloc’s Snowball Swarm',5]);
	spells[6].push(['https://www.dndbeyond.com/spells/soul-cage','Soul Cage',5]);
	spells[5].push(['https://www.dndbeyond.com/spells/steel-wind-strike','Steel Wind Strike',5]);
	spells[4].push(['https://www.dndbeyond.com/spells/storm-sphere','Storm Sphere',5]);
	spells[4].push(['https://www.dndbeyond.com/spells/summon-greater-demon','Summon Greater Demon',5]);
	spells[3].push(['https://www.dndbeyond.com/spells/summon-lesser-demons','Summon Lesser Demons',5]);
	spells[5].push(['https://www.dndbeyond.com/spells/synaptic-static','Synaptic Static',5]);
	spells[7].push(['https://www.dndbeyond.com/spells/temple-of-the-gods','Temple of the Gods',5]);
	spells[6].push(['https://www.dndbeyond.com/spells/tensers-transformation','Tenser’s Transformation',5]);
	spells[3].push(['https://www.dndbeyond.com/spells/thunder-step','Thunder Step',5]);
	spells[0].push(['https://www.dndbeyond.com/spells/thunderclap','Thunderclap',5]);
	spells[3].push(['https://www.dndbeyond.com/spells/tidal-wave','Tidal Wave',5]);
	spells[3].push(['https://www.dndbeyond.com/spells/tiny-servant','Tiny Servant',5]);
	spells[0].push(['https://www.dndbeyond.com/spells/toll-the-dead','Toll the Dead',5]);
	spells[5].push(['https://www.dndbeyond.com/spells/transmute-rock','Transmute Rock',5]);
	spells[4].push(['https://www.dndbeyond.com/spells/vitriolic-sphere','Vitriolic Sphere',5]);
	spells[5].push(['https://www.dndbeyond.com/spells/wall-of-light','Wall of Light',5]);
	spells[3].push(['https://www.dndbeyond.com/spells/wall-of-sand','Wall of Sand',5]);
	spells[3].push(['https://www.dndbeyond.com/spells/wall-of-water','Wall of Water',5]);
	spells[2].push(['https://www.dndbeyond.com/spells/warding-wind','Warding Wind',5]);
	spells[4].push(['https://www.dndbeyond.com/spells/watery-sphere','Watery Sphere',5]);
	spells[7].push(['https://www.dndbeyond.com/spells/whirlwind','Whirlwind',5]);
	spells[0].push(['https://www.dndbeyond.com/spells/word-of-radiance','Word of Radiance',5]);
	spells[5].push(['https://www.dndbeyond.com/spells/wrath-of-nature','Wrath of Nature',5]);
	spells[1].push(['https://www.dndbeyond.com/spells/zephyr-strike','Zephyr Strike',5]);

	return spells;
}